### ISSUE TITLE
Present why we are using comand line at start

### ISSUE THREAD

**Issue by tiagoams** [CefasRepRes/Git_Training#1]
Command line training was created as an after thought and is not integrated with the part 1 lecture. I think it is easier to engage with command line training after giving the motivation.

Additionally, I think it is useful to show that file and directory management can be done and are equivalent to using file manager (in any OS). It is the cd and git commands that must be done on the command line.

Another reason for using git on the command line is to get the useful git suggestions.

**Comment by jenniferagraham** [comment]
This was updated with course content in 2023.
