### ISSUE TITLE
Is OneDrive a problem?

### ISSUE THREAD

**Issue by ghost** [CefasRepRes/Git_Training#3]
Git on OneDrive sounds like a bad idea (syncing files with weird names) and I would avoid it, but perhaps I'm being pessimistic - Do we think that was part of Sarah's
trouble?

**Comment by tiagoams** [comment]
The one disadvantage I have having repos on OneDrive is the time it takes to sync .git everytime an add or commit is made. This can be taxing on poor connectivity.

The advantage is that it provides a backup to:
- uncommited changes
- unpushed changes
- untracked files

**Comment by jenniferagraham** [comment]
I don't think hosting locally in OneDrive should behave any differently to elsewhere on your PC. 
So, closing for now, but can reopen is issues become known?
