### ISSUE TITLE
Review comments from feedback

### ISSUE THREAD

**Issue by jenniferagraham** [CefasRepRes/Git_Training#5]
Reminder to check feedback here, e.g., maybe consider splitting course into two distinct sections (for beginners and then more advanced)? Cement the basics before moving on... 
https://forms.gle/7xqycdTLxEJ19GK68

**Comment by jenniferagraham** [comment]
Tiago has link to 2023 feedback. Main comments to consider here for reference: 
- note about access keys in setup instructions (becomes an issue when first push repo). 
- consider providing template example for initial exercises? (those who are newer to coding?)
- lunch options closer to venue? (note 2023 was held in JSC)
- option to host in Cefas vs UEA? 
- how to setup wikis or websites?

**Comment by tiagoams** [comment]
* consider providing template example for initial exercises? (those who are newer to coding?)

The first exercise says:
* Open the editor and create a new file poem.txt
* Copy the first verse of a poem and save.

I will suggest to the class to copy a poem from the web, but don't think that providing a template in the repo will make this easier or less confusing.

**Comment by jenniferagraham** [comment]
Comments above have been reviewed. 

- note about access keys in setup instructions (becomes an issue when first push repo).
  - Options vary with OS, so just be prepared for troubleshooting. 
  
- consider providing template example for initial exercises? (those who are newer to coding?)
  - Also reviewed in exercise S1-49. 
  - This is all about creating a new directory and adding a simple text file. Agree that providing a template is unlikely to make less confusing. 

- lunch options closer to venue? option to host in Cefas vs UEA?
  - Hosting in UEA due to balance of attendees, and therefore ease of travel and hosting. 
  - Now held in ZICER rather than JSC, so closer to food options. 

- how to setup wikis or websites?
  - wikis are mentioned as an extra form of documentation, but we don't go into detail. Suggest this is included in future TUAC sessions? Or, time permitting, can suggest as an AOB for later in the day ("Going forward with Git").
