### ISSUE TITLE
Provide example of checkout for commits

### ISSUE THREAD

**Issue by jenniferagraham** [CefasRepRes/Git_Training#6]
This is introduced when discussing detached head state - consider including earlier? (to pre-empt errors in exercise)

**Comment by davidryderuk2** [comment]
I would be tempted to suggest the following approach:

- Restoring files from the index using `git restore <PATH>`.
- Restoring files from an earlier commit using `git restore --source=<commit> -WS <PATH>`
- Unstaging files using `git restore --staged <PATH>`
- Adding or removing commits using `git reset [<mode>] [<commit>]`.
- Switching branches, creating a new branch or detaching head using `git checkout`.

That way all the 'low risk' operations like restoring files and unstaging files can be kept seperate from all the high risk operations like updating the branch, switching branches and detaching head and we can reduce the chance of people making typos, and accidently changing their commit history. 

However, I acknowledge that:

- We would probably be up against all the tutorials online suggesting people use `git checkout` and `git reset` for restoring files and unstaging files.
- It would require rewritting a lot of slides from our second session, which could introduce a lot of errors.
- There is still a warning provided with the `git restore` command suggesting it is experimental, and behaviour is subject to change, which is less than ideal.

Anyway, going back to your specific example, the suggestion would be to run the following:

`git restore --source=HEAD~1 --staged --worktree README.md`

Which should be equivilient to:

`git checkout HEAD~1 README.md `

It takes longer to type, granted, but personally I find it a bit less confusing.

**Comment by davidryderuk2** [comment]
Sorry, not sure how I ended up closing the issue.

**Comment by davidryderuk2** [comment]
Sorry, I didn't mean to close the issue. Obviously I can see my suggestion isn't ideal.

**Comment by tiagoams** [comment]
Regarding teaching `git restore` over `git checkout` I think it is easier for beginners to type and memorise shorter commands. Eventually many will use a GUI and the meanings can even be different from command line. Thus I wouldn't worry with teaching the best possible long commands.

One example we can use in the course to justify learning the command line as a universal tool is that "Revert file" in Rstudio menu does `git reset <file>` followed by `git checkout <file>`
https://stackoverflow.com/questions/36482052/rstudio-revert-button-seems-to-act-like-git-reset
Of course, `git revert` does a completely different thing, creating a new commit that reinstates a previous commit.

**Comment by tiagoams** [comment]
I will introduce `git checkout <commit>`  earlier as suggested to separate from `git checkout <commit> <path>`

**Comment by tiagoams** [comment]
I will introduce git checkout <commit> earlier as suggested to separate from git checkout <commit> <path>
