### ISSUE TITLE
Create a `quarto` demo  of course material

### ISSUE THREAD

**Issue by stephendavidgregory** [CefasRepRes/Git_Training#8]
Just the first few slides of [Introduction_GitHub_1-2023.pdf](https://github.com/CefasRepRes/Git_Training/blob/main/course-materials/Introduction_GitHub_1-2023.pdf) and (perhaps) [Command Line Cheat Sheet.pdf](https://github.com/CefasRepRes/Git_Training/blob/main/course-materials/Command%20Line%20Cheat%20Sheet.pdf).

**Comment by stephendavidgregory** [comment]
Sorry, all - I can't assign myself :)

**Comment by stephendavidgregory** [comment]
I've coded the "Introduction_Command_Line.pdf" in markdown (see "course-materials/intro-to-cmd.qmd") and compiled it to a self-contained html using [Quarto](https://quarto.org/) (see "course-materials/intro-to-cmd.html") with [reveal.js](https://quarto.org/docs/presentations/).

What do you think?

**Comment by stephendavidgregory** [comment]
Some issues with "intro-to-cmd.qmd":

- "ls = List files in directory" is small - need to make larger...

**Comment by tiagoams** [comment]
I think this is the way to go, and liked your demonstration, but can't afford the time right now to redo the 3 presentations. I suggest that we move lessons to Quarto as we can.

**Comment by jenniferagraham** [comment]
Agree that this looks good, but will take some time to convert existing content. 

In meantime, I've tidied the existing quarto files into a directory here (to avoid confusing attendees). Let me know if this breaks any links anywhere!
